AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  幕末志士 Web API template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  BakumatsuFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: BakumatsuFunction
      Handler: bakumatsu.App::handleRequest
      Runtime: java8
      MemorySize: 2048
      Events:
        NicoVideo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /nico_video
            Method: get
        YouTube:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /youtube
            Method: get
  BakumatsuApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: BakumatsuApi
      StageName: Prod
      DefinitionUri: openApi.yaml
      OpenApiVersion: 3.0.0

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BakumatsuApi:
    Description: "API Gateway endpoint URL for Prod stage for Bakumatsu function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bakumatsu/"
  BakumatsuFunction:
    Description: "Bakumatsu Lambda Function ARN"
    Value: !GetAtt BakumatsuFunction.Arn
  BakumatsuFunctionIamRole:
    Description: "Implicit IAM Role created for Bakumatsu function"
    Value: !GetAtt BakumatsuFunctionRole.Arn
